version: '3'

services:
  node_js:
    build:
      context: .
      dockerfile: ./deploy/nodejs/Dockerfile
    container_name: backend_node_js
    restart: always
    ports:
      - '8080:8080'
    env_file: .envs/.node
    volumes:
      - .:/app